services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: local_guide_db
      POSTGRES_USER: local_guide_user
      POSTGRES_PASSWORD: local_guide_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_guide_user -d local_guide_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/local_guide_service
    environment:
      DB_NAME: local_guide_db
      DB_USER: local_guide_user
      DB_PASSWORD: local_guide_password
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: "django-insecure-8ft2*$$n7i=z&go(0jcq-)9jvbdtont*)jyoh9eslnpuwx@73@o"
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             gunicorn local_guide_service.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data: