# Generated by Django 4.2.21 on 2026-06-10 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_guideproduct_travel_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guideproduct",
            name="thumbnail_url",
        ),
        migrations.CreateModel(
            name="GuideProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="guides.guideproduct",
                    ),
                ),
            ],
            options={
                "db_table": "guide_product_images",
                "ordering": ["order"],
            },
        ),
    ]
